### ISSUE TITLE
[FEATURE] Go Public

### ISSUE THREAD

**Issue by Marcel2603** [ESELdevelopment/ecmanager#12]
### Problem Description

We want to go public, so that we can use some features, which are currently premium only

### Desired Solution

- set repo to public
- enforce protected main branch
- enable draft PRs

**Comment by Marcel2603** [comment]
# HTR
- check that the repo is public (open private tab and paste repo url)
- try to push to main 🗡️ 
- sie #14 for draft mr

**Comment by LaurinStreng** [comment]
h2. Review
* Repos is public (/)
* you cant push to main (/)
* You can set a mr to draft
