### ISSUE TITLE
Implement tui with starting page

### ISSUE THREAD

**Issue by tzabbi** [ESELdevelopment/ecmanager#2]
To get the first tui experience we need the go lib tview. In this ticket we want to implement tview and a nice and simple start page.

**AC:**
* tview is implemented
* start page is created
* tests are written

_Notes:_
* https://github.com/rivo/tview

**Comment by Marcel2603** [comment]
I would recommend [bubbletea](https://github.com/charmbracelet/bubbletea) with [bubbles](https://github.com/charmbracelet/bubbles) as components and [lipgloss](https://github.com/charmbracelet/lipgloss) for styling

Looks why nicer than tview :D

**Comment by tzabbi** [comment]
yeah it's fine for me

**Comment by LaurinStreng** [comment]
I just start with eval in here maybe we will put it somewhere else but i have no idea where so lets go :D

WIP:
gol tui:

1. Bubbletea
2. termui
3. tview

**Comment by Marcel2603** [comment]
It will be solved in #5 or?

**Comment by tzabbi** [comment]
Yes you are true. So we should first implement #5

**Comment by Marcel2603** [comment]
We use this ticket for an eval, to know which framework we want to use.
