### ISSUE TITLE
AWS ECS API connection

### ISSUE THREAD

**Issue by tzabbi** [ESELdevelopment/ecmanager#3]
In this ticket we want to implement the AWS API connection that we can get all necesarry information to show containers, logs, network ...
To mock the AWS connection we can use: https://docs.getmoto.org/en/latest/docs/server_mode.html.
Simple use case get ecs cluster.

**AC:**
* We can connect to AWS API
* Tests are written

**Comment by Marcel2603** [comment]
# How To Review
view the PR :D https://github.com/ESELdevelopment/ecmanager/pull/14#issuecomment-2356976077
