### ISSUE TITLE
implement mkdocs

### ISSUE THREAD

**Issue by tzabbi** [ESELdevelopment/ecmanager#5]
To provide the best documentation on earth, we choose the best tool on earth: mkdocs
In this documenation we want to store our learnings, and general documenation. 

**AC:**
* You can run mkdocs locally via container.

**Comment by LaurinStreng** [comment]
Should we consider to add gitlab pages workflow here @tzabbi @Marcel2603 ?

**Comment by LaurinStreng** [comment]
or do we want to just run it localy?

**Comment by Marcel2603** [comment]
Go for it, gh pages should work on public repos. But pls test if we can run the pipeline only if we change something in the mkdocs folder :)

**Comment by tzabbi** [comment]
As @Marcel2603 mentioned, we also want to implement github pages. But we need to figure out if we want two documentations, internal and public. For now we should put everything in the public docs :)

**Comment by LaurinStreng** [comment]
HTR  in #15
