### ISSUE TITLE
Layout of ecmanager

### ISSUE THREAD

**Issue by tzabbi** [ESELdevelopment/ecmanager#6]
We want provide a really nice UX with the UI, so we have to produce a really useful layout of our UI. Maybe we can you figma for it but not sure.

**AC:**
* A really clear, simple and useful layout is created

_Notes:_
* https://www.figma.com/

**Comment by Marcel2603** [comment]
i will cancle this issue, its just a little bit to big. We want to create the tui dynamically :)
