### ISSUE TITLE
Default view of ecmanager

### ISSUE THREAD

**Issue by tzabbi** [ESELdevelopment/ecmanager#8]
In this ticket we want to create the default view if no cluster is selected. This includes the check if you are able to load the cluster from AWS.

*AC:*
* List of clusters will be shown at the start of ecmanager.
* Check that you are able to connect to AWS is implemented.

**Comment by Marcel2603** [comment]
i will close this ticket, its at the current stage to big / unspecific. It will get replaced with smaller tickets (for examle: create clusterlist, etc).
